import 'package:cloud_firestore/cloud_firestore.dart';

/// מודל תרגיל
class ExerciseModel {
  final String id;
  final String name;
  final String description;
  final int orderIndex;
  final bool isCompleted;
  final DateTime? completedAt;
  final DateTime createdAt;
  final String? videoUrl;
  final String level; // רמת התרגיל: "רמת בסיס", "רמה 1", "רמה 2", "רמה 3", "רמה 4", "רמה 5"

  ExerciseModel({
    required this.id,
    required this.name,
    required this.description,
    required this.orderIndex,
    this.isCompleted = false,
    this.completedAt,
    required this.createdAt,
    this.videoUrl,
    this.level = 'רמת בסיס',
  });

  /// המרה מ-Firestore
  factory ExerciseModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return ExerciseModel(
      id: doc.id,
      name: data['name'] ?? '',
      description: data['description'] ?? '',
      orderIndex: data['orderIndex'] ?? 0,
      isCompleted: data['isCompleted'] ?? false,
      completedAt: (data['completedAt'] as Timestamp?)?.toDate(),
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      videoUrl: data['videoUrl'],
      level: data['level'] ?? 'רמת בסיס',
    );
  }

  /// המרה ל-Firestore
  Map<String, dynamic> toFirestore() {
    return {
      'name': name,
      'description': description,
      'orderIndex': orderIndex,
      'isCompleted': isCompleted,
      'completedAt': completedAt != null ? Timestamp.fromDate(completedAt!) : null,
      'createdAt': Timestamp.fromDate(createdAt),
      'videoUrl': videoUrl,
      'level': level,
    };
  }

  /// העתקה עם שינויים
  ExerciseModel copyWith({
    String? id,
    String? name,
    String? description,
    int? orderIndex,
    bool? isCompleted,
    DateTime? completedAt,
    DateTime? createdAt,
    String? videoUrl,
    String? level,
  }) {
    return ExerciseModel(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      orderIndex: orderIndex ?? this.orderIndex,
      isCompleted: isCompleted ?? this.isCompleted,
      completedAt: completedAt ?? this.completedAt,
      createdAt: createdAt ?? this.createdAt,
      videoUrl: videoUrl ?? this.videoUrl,
      level: level ?? this.level,
    );
  }
}

/// רשימת תרגילים מוגדרים מראש
class DefaultExercises {
  static final List<Map<String, dynamic>> exercises = [
    // רמת בסיס (16 תרגילים)
    {
      'name': 'אנשופלה',
      'description': 'אנשופלה',
      'orderIndex': 1,
      'videoUrl': 'https://youtu.be/CRriCdGAWSw',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אנשופלה דובלה',
      'description': 'אנשופלה דובלה',
      'orderIndex': 2,
      'videoUrl': 'https://youtu.be/8C-rnq2XEDQ',
      'level': 'רמת בסיס',
    },
    {
      'name': 'מיאמי',
      'description': 'מיאמי',
      'orderIndex': 3,
      'videoUrl': 'https://youtu.be/U6WG7TWGFYA',
      'level': 'רמת בסיס',
    },
    {
      'name': 'קנדאדו',
      'description': 'קנדאדו',
      'orderIndex': 4,
      'videoUrl': 'https://youtu.be/qIP_56dpgwU',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אל אונו',
      'description': 'אל אונו',
      'orderIndex': 5,
      'videoUrl': 'https://youtu.be/YeabcooNnFM',
      'level': 'רמת בסיס',
    },
    {
      'name': 'דאמא קון אונה, דוס, וטרס',
      'description': 'דאמא קון אונה, דוס, וטרס',
      'orderIndex': 6,
      'videoUrl': 'https://youtu.be/iB5ZIctXz7E',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אנשופלה קון אקסיבלה',
      'description': 'אנשופלה קון אקסיבלה',
      'orderIndex': 7,
      'videoUrl': 'https://youtu.be/mRFTUrbHAUU',
      'level': 'רמת בסיס',
    },
    {
      'name': 'און פליי',
      'description': 'און פליי',
      'orderIndex': 8,
      'videoUrl': 'https://youtu.be/FfNn7orN9FA',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אנשופלה קון וואלטה',
      'description': 'אנשופלה קון וואלטה',
      'orderIndex': 9,
      'videoUrl': 'https://youtu.be/Oe8FI3auTnl',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אנשופלה קון אקסיבלה דובלה',
      'description': 'אנשופלה קון אקסיבלה דובלה',
      'orderIndex': 10,
      'videoUrl': 'https://youtu.be/PzIPvX_CwmA',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אנשופלה אי דאמה',
      'description': 'אנשופלה אי דאמה',
      'orderIndex': 11,
      'videoUrl': 'https://youtu.be/Y7k8XyuloRY',
      'level': 'רמת בסיס',
    },
    {
      'name': 'קנטאקי',
      'description': 'קנטאקי',
      'orderIndex': 12,
      'videoUrl': 'https://youtu.be/hUjGh_ipsFc',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אנשופלה קומפליקדו',
      'description': 'אנשופלה קומפליקדו',
      'orderIndex': 13,
      'videoUrl': 'https://youtu.be/Hq2OBXdCIfk',
      'level': 'רמת בסיס',
    },
    {
      'name': 'אל אונו מגניב',
      'description': 'אל אונו מגניב',
      'orderIndex': 14,
      'videoUrl': 'https://youtu.be/vf_ql2e7NQk',
      'level': 'רמת בסיס',
    },
    {
      'name': 'פסטיבל ביילנדו (בלאגון) קרמלו',
      'description': 'פסטיבל ביילנדו (בלאגון) קרמלו',
      'orderIndex': 15,
      'videoUrl': 'https://youtu.be/BODGK9nNOXc',
      'level': 'רמת בסיס',
    },
    {
      'name': 'הומברס אל סנטרו + לה פלוטה',
      'description': 'הומברס אל סנטרו + לה פלוטה',
      'orderIndex': 16,
      'videoUrl': 'https://youtu.be/mv2yYkPyog8',
      'level': 'רמת בסיס',
    },

    // רמה 1 (15 תרגילים)
    {
      'name': 'לנטו',
      'description': 'לנטו',
      'orderIndex': 17,
      'videoUrl': 'https://youtu.be/_SJbUn7-i6U',
      'level': 'רמה 1',
    },
    {
      'name': 'וסילהלה',
      'description': 'וסילהלה',
      'orderIndex': 18,
      'videoUrl': 'https://youtu.be/9qvB4DV8gaM',
      'level': 'רמה 1',
    },
    {
      'name': 'וסילהלה וואלטה',
      'description': 'וסילהלה וואלטה',
      'orderIndex': 19,
      'videoUrl': 'https://youtu.be/jxiX4L4JMiw',
      'level': 'רמה 1',
    },
    {
      'name': 'אנשופלה דספלוטות',
      'description': 'אנשופלה דספלוטות',
      'orderIndex': 20,
      'videoUrl': 'https://youtu.be/L5tnbOWhZ0g',
      'level': 'רמה 1',
    },
    {
      'name': 'קנטאקי סודר',
      'description': 'קנטאקי סודר',
      'orderIndex': 21,
      'videoUrl': 'https://youtu.be/72zJH9Ba4iU',
      'level': 'רמה 1',
    },
    {
      'name': 'פלמנגו',
      'description': 'פלמנגו',
      'orderIndex': 22,
      'videoUrl': 'https://youtu.be/xFoHM96t03o',
      'level': 'רמה 1',
    },
    {
      'name': 'אנשופלה טמפנו אספניה+טארו (פור אריבה, פור אבכו)',
      'description': 'אנשופלה טמפנו אספניה+טארו (פור אריבה, פור אבכו)',
      'orderIndex': 23,
      'videoUrl': 'https://youtu.be/gxtOTJcCkiU',
      'level': 'רמה 1',
    },
    {
      'name': 'פרימה',
      'description': 'פרימה',
      'orderIndex': 24,
      'videoUrl': 'https://youtu.be/2bQfSw_IXfA',
      'level': 'רמה 1',
    },
    {
      'name': 'אדיוֹס',
      'description': 'אדיוֹס',
      'orderIndex': 25,
      'videoUrl': 'https://youtu.be/3khWERxosok',
      'level': 'רמה 1',
    },
    {
      'name': 'פסטיבל בואנו מאלו',
      'description': 'פסטיבל בואנו מאלו',
      'orderIndex': 26,
      'videoUrl': 'https://youtu.be/ah6eRsBgrbU',
      'level': 'רמה 1',
    },
    {
      'name': 'הומברס אל סנטרו+לה פלוטה קלאווה',
      'description': 'הומברס אל סנטרו+לה פלוטה קלאווה',
      'orderIndex': 27,
      'videoUrl': 'https://youtu.be/Ye6saUGo07o',
      'level': 'רמה 1',
    },
    {
      'name': 'הומברס אל סנטרו+לה פלוטה לוקה',
      'description': 'הומברס אל סנטרו+לה פלוטה לוקה',
      'orderIndex': 28,
      'videoUrl': 'https://youtu.be/rgg__zfo7bU',
      'level': 'רמה 1',
    },
    {
      'name': 'פרימה קון לה הרמנה',
      'description': 'פרימה קון לה הרמנה',
      'orderIndex': 29,
      'videoUrl': 'https://youtu.be/b8DnNDZS7jA',
      'level': 'רמה 1',
    },
    {
      'name': 'פרימה לחץ',
      'description': 'פרימה לחץ',
      'orderIndex': 30,
      'videoUrl': 'https://youtu.be/DJAOo27sHXg',
      'level': 'רמה 1',
    },
    {
      'name': 'דוס קון דוס',
      'description': 'דוס קון דוס',
      'orderIndex': 31,
      'videoUrl': 'https://youtu.be/Xglfs5J6mv8',
      'level': 'רמה 1',
    },

    // רמה 2 (13 תרגילים)
    {
      'name': 'סנטנה אי סינקו',
      'description': 'סנטנה אי סינקו',
      'orderIndex': 32,
      'videoUrl': 'https://youtu.be/mVj_A7PUdJg',
      'level': 'רמה 2',
    },
    {
      'name': 'דובלה פליי+טריפל פליי',
      'description': 'דובלה פליי+טריפל פליי',
      'orderIndex': 33,
      'videoUrl': 'https://youtu.be/Rm8jJqKE1bY',
      'level': 'רמה 2',
    },
    {
      'name': 'סנטנה',
      'description': 'סנטנה',
      'orderIndex': 34,
      'videoUrl': 'https://youtu.be/srEdYnTbv0k',
      'level': 'רמה 2',
    },
    {
      'name': 'סייטה',
      'description': 'סייטה',
      'orderIndex': 35,
      'videoUrl': 'https://youtu.be/ri5wYDgAsb8',
      'level': 'רמה 2',
    },
    {
      'name': 'הוואנה',
      'description': 'הוואנה',
      'orderIndex': 36,
      'videoUrl': 'https://youtu.be/UV6JKbHSOlE',
      'level': 'רמה 2',
    },
    {
      'name': 'אנשופלה קוקה קולה (עם סיבוב)',
      'description': 'אנשופלה קוקה קולה (עם סיבוב)',
      'orderIndex': 37,
      'videoUrl': 'https://youtu.be/UgvhPi6y1JI',
      'level': 'רמה 2',
    },
    {
      'name': 'גואפאה סלייד',
      'description': 'גואפאה סלייד',
      'orderIndex': 38,
      'videoUrl': 'https://youtu.be/YZMBJsk4GGQ',
      'level': 'רמה 2',
    },
    {
      'name': 'סייטה קוקה קולה (עם סיבוב)',
      'description': 'סייטה קוקה קולה (עם סיבוב)',
      'orderIndex': 39,
      'videoUrl': 'https://youtu.be/5Xmq2FZS36w',
      'level': 'רמה 2',
    },
    {
      'name': 'אל קמינו',
      'description': 'אל קמינו',
      'orderIndex': 40,
      'videoUrl': 'https://youtu.be/QI9ZZkRDIN8',
      'level': 'רמה 2',
    },
    {
      'name': 'סרטון הסבר חמוד על אל קמינו',
      'description': 'סרטון הסבר חמוד על אל קמינו',
      'orderIndex': 41,
      'videoUrl': 'https://youtu.be/0XiyuAE_tUk',
      'level': 'רמה 2',
    },
    {
      'name': 'סייטה מודרנו',
      'description': 'סייטה מודרנו',
      'orderIndex': 42,
      'videoUrl': 'https://youtu.be/YPDnM5YSHdw',
      'level': 'רמה 2',
    },
    {
      'name': 'מריו',
      'description': 'מריו',
      'orderIndex': 43,
      'videoUrl': 'https://youtu.be/F06HpxI47IM',
      'level': 'רמה 2',
    },
    {
      'name': 'סייטה מודרנו כתפיים',
      'description': 'סייטה מודרנו כתפיים',
      'orderIndex': 44,
      'videoUrl': 'https://youtu.be/Dc8Gs8jOGCw',
      'level': 'רמה 2',
    },

    // רמה 3 (16 תרגילים)
    {
      'name': 'דדו',
      'description': 'דדו',
      'orderIndex': 45,
      'videoUrl': 'https://youtu.be/4tP4hCu_GNY',
      'level': 'רמה 3',
    },
    {
      'name': 'לאסו',
      'description': 'לאסו',
      'orderIndex': 46,
      'videoUrl': 'https://youtu.be/y0dq2zUKI50',
      'level': 'רמה 3',
    },
    {
      'name': 'דדו סבוריאדו',
      'description': 'דדו סבוריאדו',
      'orderIndex': 47,
      'videoUrl': 'https://youtu.be/3gzg8BdTvBk',
      'level': 'רמה 3',
    },
    {
      'name': 'פסאלה',
      'description': 'פסאלה',
      'orderIndex': 48,
      'videoUrl': 'https://youtu.be/BznEuRFOpwk',
      'level': 'רמה 3',
    },
    {
      'name': 'דדו קומפליקדו',
      'description': 'דדו קומפליקדו',
      'orderIndex': 49,
      'videoUrl': 'https://youtu.be/pO6vUAoPgKs',
      'level': 'רמה 3',
    },
    {
      'name': 'סומבררו',
      'description': 'סומבררו',
      'orderIndex': 50,
      'videoUrl': 'https://youtu.be/sAUeJyOy2nc',
      'level': 'רמה 3',
    },
    {
      'name': 'אטרבידו',
      'description': 'אטרבידו',
      'orderIndex': 51,
      'videoUrl': 'https://youtu.be/Ib9Kt0dN1K8',
      'level': 'רמה 3',
    },
    {
      'name': 'מונטניה רוסה',
      'description': 'מונטניה רוסה',
      'orderIndex': 52,
      'videoUrl': 'https://youtu.be/mKciEoZfqns',
      'level': 'רמה 3',
    },
    {
      'name': 'סומבררו דובלה',
      'description': 'סומבררו דובלה',
      'orderIndex': 53,
      'videoUrl': 'https://youtu.be/nLo6Jc_a8GI',
      'level': 'רמה 3',
    },
    {
      'name': 'חוואנה לה קובנה',
      'description': 'חוואנה לה קובנה',
      'orderIndex': 54,
      'videoUrl': 'https://youtu.be/AE_VT_ju9bs',
      'level': 'רמה 3',
    },
    {
      'name': 'אל דוס',
      'description': 'אל דוס',
      'orderIndex': 55,
      'videoUrl': 'https://youtu.be/FXZrv_8HWmw',
      'level': 'רמה 3',
    },
    {
      'name': 'מאנוס טרס',
      'description': 'מאנוס טרס',
      'orderIndex': 56,
      'videoUrl': 'https://youtu.be/GHhN1ZXP6N4',
      'level': 'רמה 3',
    },
    {
      'name': 'בסו',
      'description': 'בסו',
      'orderIndex': 57,
      'videoUrl': 'https://youtu.be/J5WPB1ilHig',
      'level': 'רמה 3',
    },
    {
      'name': 'אברסלה',
      'description': 'אברסלה',
      'orderIndex': 58,
      'videoUrl': 'https://youtu.be/OLIp2lc3cJk',
      'level': 'רמה 3',
    },
    {
      'name': 'בלסרו',
      'description': 'בלסרו',
      'orderIndex': 59,
      'videoUrl': 'https://youtu.be/_5_XGNUpg3s',
      'level': 'רמה 3',
    },
    {
      'name': 'אבניקו',
      'description': 'אבניקו',
      'orderIndex': 60,
      'videoUrl': 'https://youtu.be/if-8wCtCpi8',
      'level': 'רמה 3',
    },

    // רמה 4 (8 תרגילים)
    {
      'name': 'וואלטס',
      'description': 'וואלטס',
      'orderIndex': 61,
      'videoUrl': 'https://youtu.be/Qk3HQ08s24I',
      'level': 'רמה 4',
    },
    {
      'name': 'פין',
      'description': 'פין',
      'orderIndex': 62,
      'videoUrl': 'https://youtu.be/HleaVHClaWw',
      'level': 'רמה 4',
    },
    {
      'name': 'סייטה לוקה',
      'description': 'סייטה לוקה',
      'orderIndex': 63,
      'videoUrl': 'https://youtu.be/kBedky8yoeU',
      'level': 'רמה 4',
    },
    {
      'name': 'סנטנה אי סינקו קומפליקדו',
      'description': 'סנטנה אי סינקו קומפליקדו',
      'orderIndex': 64,
      'videoUrl': 'https://youtu.be/zm1t5WytI6U',
      'level': 'רמה 4',
    },
    {
      'name': 'סואבה',
      'description': 'סואבה',
      'orderIndex': 65,
      'videoUrl': 'https://youtu.be/eZxXD07PmD8',
      'level': 'רמה 4',
    },
    {
      'name': 'פין לה סאבור',
      'description': 'פין לה סאבור',
      'orderIndex': 66,
      'videoUrl': 'https://youtu.be/_OglogoizMQ',
      'level': 'רמה 4',
    },
    {
      'name': 'אנשופלה קוקה קולה פור אטרס',
      'description': 'אנשופלה קוקה קולה פור אטרס',
      'orderIndex': 67,
      'videoUrl': 'https://youtu.be/tYZBt4nYLxE',
      'level': 'רמה 4',
    },
    {
      'name': 'חירו',
      'description': 'חירו',
      'orderIndex': 68,
      'videoUrl': 'https://youtu.be/_W_QL3ZFOJc',
      'level': 'רמה 4',
    },

    // רמה 5 (24 תרגילים)
    {
      'name': 'סייטה מגניב',
      'description': 'סייטה מגניב',
      'orderIndex': 69,
      'videoUrl': 'https://youtu.be/aK7zCMrnOvM',
      'level': 'רמה 5',
    },
    {
      'name': 'נובנטה',
      'description': 'נובנטה',
      'orderIndex': 70,
      'videoUrl': 'https://youtu.be/Ez2YHMovv3E',
      'level': 'רמה 5',
    },
    {
      'name': 'סנטנה אי נואבה',
      'description': 'סנטנה אי נואבה',
      'orderIndex': 71,
      'videoUrl': 'https://youtu.be/5AcssxpBPco',
      'level': 'רמה 5',
    },
    {
      'name': 'לה ג\'ני',
      'description': 'לה ג\'ני',
      'orderIndex': 72,
      'videoUrl': 'https://youtu.be/H6LVfGfn-78',
      'level': 'רמה 5',
    },
    {
      'name': 'קולון',
      'description': 'קולון',
      'orderIndex': 73,
      'videoUrl': 'https://youtu.be/1QqBR5eFqe8',
      'level': 'רמה 5',
    },
    {
      'name': 'טרומפו',
      'description': 'טרומפו',
      'orderIndex': 74,
      'videoUrl': 'https://youtu.be/VXLGrB6HLFw',
      'level': 'רמה 5',
    },
    {
      'name': 'אנשופלה הוזדה לה רוסס',
      'description': 'אנשופלה הוזדה לה רוסס',
      'orderIndex': 75,
      'videoUrl': 'https://youtu.be/kMFrYNx1ZPA',
      'level': 'רמה 5',
    },
    {
      'name': 'אנשופלה אי דאמה אבחח',
      'description': 'אנשופלה אי דאמה אבחח',
      'orderIndex': 76,
      'videoUrl': 'https://youtu.be/tTq7H1c50zA',
      'level': 'רמה 5',
    },
    {
      'name': 'פין חורף',
      'description': 'פין חורף',
      'orderIndex': 77,
      'videoUrl': 'https://youtu.be/T3h8GqMNCnA',
      'level': 'רמה 5',
    },
    {
      'name': 'לה בומבה',
      'description': 'לה בומבה',
      'orderIndex': 78,
      'videoUrl': 'https://youtu.be/OfH_y9IcWbk',
      'level': 'רמה 5',
    },
    {
      'name': 'קפה הפוך',
      'description': 'קפה הפוך',
      'orderIndex': 79,
      'videoUrl': 'https://youtu.be/c17e9UoJy6I',
      'level': 'רמה 5',
    },
    {
      'name': 'אבנינטה',
      'description': 'אבנינטה',
      'orderIndex': 80,
      'videoUrl': 'https://youtu.be/OGlisOIn9ro',
      'level': 'רמה 5',
    },
    {
      'name': 'אל אונו קומפליקדו',
      'description': 'אל אונו קומפליקדו',
      'orderIndex': 81,
      'videoUrl': 'https://youtu.be/i9oyPp2ZKX0',
      'level': 'רמה 5',
    },
    {
      'name': 'אבניקו קומפליקדו',
      'description': 'אבניקו קומפליקדו',
      'orderIndex': 82,
      'videoUrl': 'https://youtu.be/Ky1G5tVhrvM',
      'level': 'רמה 5',
    },
    {
      'name': 'בסו פור דה באחו',
      'description': 'בסו פור דה באחו',
      'orderIndex': 83,
      'videoUrl': 'https://youtu.be/_Q2f2sPr87I',
      'level': 'רמה 5',
    },
    {
      'name': 'סברוסורה',
      'description': 'סברוסורה',
      'orderIndex': 84,
      'videoUrl': 'https://youtu.be/2AnoY6z1DXo',
      'level': 'רמה 5',
    },
    {
      'name': 'לה קודרה',
      'description': 'לה קודרה',
      'orderIndex': 85,
      'videoUrl': 'https://youtu.be/t8_3AoiiL_M',
      'level': 'רמה 5',
    },
    {
      'name': 'סחרחרות',
      'description': 'סחרחרות',
      'orderIndex': 86,
      'videoUrl': 'https://youtu.be/-eewpS2q9Uw',
      'level': 'רמה 5',
    },
    {
      'name': 'בוטה לה',
      'description': 'בוטה לה',
      'orderIndex': 87,
      'videoUrl': 'https://youtu.be/6taEVDw5Ifg',
      'level': 'רמה 5',
    },
    {
      'name': 'סייטה מילניום',
      'description': 'סייטה מילניום',
      'orderIndex': 88,
      'videoUrl': 'https://youtu.be/aadHZSFnOPo',
      'level': 'רמה 5',
    },
    {
      'name': 'סטטנה אנרדטה (לעשות תרגיל על שם תלמיד)',
      'description': 'סטטנה אנרדטה (לעשות תרגיל על שם תלמיד)',
      'orderIndex': 89,
      'videoUrl': 'https://youtu.be/O3J3cvzhT7E',
      'level': 'רמה 5',
    },
    {
      'name': 'אואצ\'י',
      'description': 'אואצ\'י',
      'orderIndex': 90,
      'videoUrl': 'https://youtu.be/TmC6jN-keJ4',
      'level': 'רמה 5',
    },
    {
      'name': 'אואצ\'י קומפליקדו',
      'description': 'אואצ\'י קומפליקדו',
      'orderIndex': 91,
      'videoUrl': 'https://youtu.be/scpQXVH0nzw',
      'level': 'רמה 5',
    },
    {
      'name': 'צ\'אפירה',
      'description': 'צ\'אפירה',
      'orderIndex': 92,
      'videoUrl': 'https://youtu.be/AUfcXbJoDQM',
      'level': 'רמה 5',
    },
  ];
}
